package cliente.presentacion;

import cliente.logica.ConexionJsockets;
import com.toedter.calendar.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.*;

/**
 *
 * @author Mis hijos
 */
public class VentanaRegistro extends javax.swing.JFrame {

    /** Creates new form VentanaRegistro */
    public VentanaRegistro() {
        initComponents();
        //inicializarComponentesPropios();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTxtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtLastName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDCFechaNac = new com.toedter.calendar.JDateChooser();
        jTxtNickname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFdRegister = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFdConfirm = new javax.swing.JPasswordField();
        jTxtAvatar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBChooseImg = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jBAceptar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTxtName.setFont(new java.awt.Font("Calibri", 0, 12));
        jTxtName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTxtName.setBounds(150, 30, 184, 18);
        jLayeredPane1.add(jTxtName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Name");
        jLabel1.setBounds(92, 30, 40, 17);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Last Name");
        jLabel2.setBounds(67, 70, 70, 17);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTxtLastName.setFont(new java.awt.Font("Calibri", 0, 12));
        jTxtLastName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTxtLastName.setBounds(150, 70, 184, 18);
        jLayeredPane1.add(jTxtLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Birth Date");
        jLabel7.setBounds(70, 110, 70, 17);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDCFechaNac.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jDCFechaNac.setFont(new java.awt.Font("Calibri", 0, 12));
        jDCFechaNac.setBounds(150, 110, 204, 23);
        jLayeredPane1.add(jDCFechaNac, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTxtNickname.setFont(new java.awt.Font("Calibri", 0, 12));
        jTxtNickname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTxtNickname.setBounds(150, 160, 184, 18);
        jLayeredPane1.add(jTxtNickname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Nickname");
        jLabel3.setBounds(70, 160, 70, 17);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("Password");
        jLabel4.setBounds(70, 200, 70, 17);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPasswordFdRegister.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jPasswordFdRegister.setBounds(150, 200, 184, 23);
        jLayeredPane1.add(jPasswordFdRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Confirm Password");
        jLabel5.setBounds(20, 240, 110, 17);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPasswordFdConfirm.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jPasswordFdConfirm.setBounds(150, 240, 184, 23);
        jLayeredPane1.add(jPasswordFdConfirm, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTxtAvatar.setEditable(false);
        jTxtAvatar.setFont(new java.awt.Font("Calibri", 0, 12));
        jTxtAvatar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTxtAvatar.setBounds(150, 280, 184, 18);
        jLayeredPane1.add(jTxtAvatar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Avatar");
        jLabel6.setBounds(90, 280, 40, 17);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBChooseImg.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jBChooseImg.setText("...");
        jBChooseImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChooseImgActionPerformed(evt);
            }
        });
        jBChooseImg.setBounds(340, 280, 22, 21);
        jLayeredPane1.add(jBChooseImg, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButtonCancel.setFont(new java.awt.Font("Calibri", 1, 14));
        jButtonCancel.setForeground(new java.awt.Color(153, 51, 0));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jButtonCancel.setBounds(230, 330, 80, 25);
        jLayeredPane1.add(jButtonCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBAceptar.setFont(new java.awt.Font("Calibri", 1, 12));
        jBAceptar.setForeground(new java.awt.Color(153, 0, 0));
        jBAceptar.setText("OK");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });
        jBAceptar.setBounds(147, 330, 60, 25);
        jLayeredPane1.add(jBAceptar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/presentacion/resources/Fondo-Madera1.jpg"))); // NOI18N
        jLabel8.setBounds(0, -6, 420, 410);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBChooseImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChooseImgActionPerformed
        // TODO add your handling code here:
        //System.out.println("cargaa");
        Imagenes ventanaImagenes;
        ventanaImagenes = new Imagenes(this, jTxtAvatar);//, jTxtName, jTxtLastName, jTxtNickname, jPasswordFdRegister, jTxtAvatar);
        ventanaImagenes.setVisible(true);
    }//GEN-LAST:event_jBChooseImgActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_jButtonCancelActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        // TODO add your handling code here:

        if (jTxtName.getText().equalsIgnoreCase("")
                || jTxtLastName.getText().equalsIgnoreCase("")
                || jTxtNickname.getText().equalsIgnoreCase("")
                || jPasswordFdRegister.getText().equalsIgnoreCase("")
                || jPasswordFdConfirm.getText().equalsIgnoreCase("")
                || jTxtAvatar.getText().equalsIgnoreCase("")
                || getFecha(jDCFechaNac).equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "All fields must be written in.");
        } else {

            if (jPasswordFdRegister.getText().equalsIgnoreCase(jPasswordFdConfirm.getText())) {
                Imagenes icono = new Imagenes(this);
                String avatar = icono.setAvatar();
                System.out.println("avatar = " + avatar);
                //jTxtAvatar.setText(avatar);
                String mensaje = ConexionJsockets.solicitudServidor3(jTxtName, jTxtLastName, jTxtNickname, jPasswordFdRegister, avatar, getFecha(jDCFechaNac));

                if (mensaje.equals("TRUE")) {
                    System.out.println(mensaje);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Nickname already exists, please try another one.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Password and Confirmed Password do not match.");
            }
        }
}//GEN-LAST:event_jBAceptarActionPerformed


    public static String getFecha(JDateChooser Jdc)
     {
        Calendar fechadate;
        fechadate=Jdc.getCalendar();
        SimpleDateFormat xlsDate;
        xlsDate = new SimpleDateFormat("dd/MM/yyyy");
        String auxiliar = xlsDate.format(fechadate.getTime());

        return auxiliar;

      }
    /*public void inicializarComponentesPropios(){
    Conector.inicializarEstructuras();
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBChooseImg;
    private javax.swing.JButton jButtonCancel;
    private com.toedter.calendar.JDateChooser jDCFechaNac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordFdConfirm;
    private javax.swing.JPasswordField jPasswordFdRegister;
    private javax.swing.JTextField jTxtAvatar;
    private javax.swing.JTextField jTxtLastName;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtNickname;
    // End of variables declaration//GEN-END:variables
}
