package cliente.presentacion;
import cliente.logica.ConexionJsockets;
import javax.swing.JOptionPane;

public class VentanaLogin extends javax.swing.JFrame {

    /** Creates new form VentanaLogin */
    public VentanaLogin() {
        initComponents();
        this.setTitle("iDomino");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbliDomino = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblNickname = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign in");
        setBackground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.red);

        lbliDomino.setFont(new java.awt.Font("Brush Script MT", 1, 36));
        lbliDomino.setForeground(new java.awt.Color(255, 204, 0));
        lbliDomino.setText("iDomino");
        lbliDomino.setBounds(190, 0, 108, 45);
        jLayeredPane1.add(lbliDomino, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtNickname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        txtNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicknameActionPerformed(evt);
            }
        });
        txtNickname.setBounds(200, 60, 89, 16);
        jLayeredPane1.add(txtNickname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 0)));
        txtPassword.setBounds(200, 100, 89, 16);
        jLayeredPane1.add(txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblNickname.setFont(new java.awt.Font("Calibri", 1, 14));
        lblNickname.setForeground(new java.awt.Color(255, 204, 0));
        lblNickname.setText("Nickname");
        lblNickname.setBounds(130, 60, 60, 17);
        jLayeredPane1.add(lblNickname, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblPassword.setFont(new java.awt.Font("Calibri", 1, 14));
        lblPassword.setForeground(new java.awt.Color(255, 204, 0));
        lblPassword.setText("Password");
        lblPassword.setBounds(130, 100, 60, 17);
        jLayeredPane1.add(lblPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnOK.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnOK.setForeground(new java.awt.Color(153, 51, 0));
        btnOK.setText("Sign in");
        btnOK.setBorder(null);
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        btnOK.setBounds(130, 130, 60, 20);
        jLayeredPane1.add(btnOK, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnCancel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(153, 51, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        btnCancel.setBounds(210, 130, 80, 20);
        jLayeredPane1.add(btnCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnSignUp.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(153, 51, 0));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        btnSignUp.setBounds(310, 170, 80, 20);
        jLayeredPane1.add(btnSignUp, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        jLabel2.setText("Not registered?");
        jLabel2.setBounds(230, 170, 77, 16);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/presentacion/resources/Fondo-Madera1.jpg"))); // NOI18N
        jLabel1.setBounds(-6, -6, 420, 230);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este método llama a la ventana de registro
     * @param evt
     */
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        VentanaRegistro ventana = new VentanaRegistro();
        ventana.setVisible(true);
        ventana.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * Este método cierra la ventana de login
     * @param evt
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
}//GEN-LAST:event_btnCancelActionPerformed

    /**
     * Este método comprueba que no estén vacios los texfield de nickname y password, si es asi, envia un mensaje, en caso
     * contrario llama al servidor para que compruebe los datos del cliente.
     * @param evt
     */
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        if (txtNickname.getText().equalsIgnoreCase("") || txtPassword.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "All fields must be written in.");
        } else {
            String mensaje = ConexionJsockets.solicitudServidor1(txtNickname, txtPassword);
            String[] subArg = mensaje.split(":");
            mensaje = subArg[0];
            if (mensaje.equals("TRUE")) {

                VentanaMenu ventanaMenu;
                ventanaMenu = new VentanaMenu(this);
                ventanaMenu.setVisible(true);
                ventanaMenu.setLocationRelativeTo(null);

                ventanaMenu.setDatosUsuario(txtPassword.getText(),txtNickname.getText(),subArg[1], subArg[2], subArg[3],subArg[4]);

                /*VentanaModificar ventanaModificar;
                ventanaModificar = new VentanaModificar(this);

                ventanaModificar.setDatosUsuario(txtPassword.getText(),txtNickname.getText(),subArg[1], subArg[2], subArg[3],subArg[4]);*/

                this.dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Invalid Nickname or Password. Please try again");
                txtNickname.setText("");
                txtPassword.setText("");
            }
        }
}//GEN-LAST:event_btnOKActionPerformed

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtNicknameActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lbliDomino;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
