/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaModificar.java
 *
 * Created on 22/08/2010, 12:59:00
 */

package cliente.presentacion;
import cliente.logica.ConexionJsockets;
import javax.swing.*;
import com.toedter.calendar.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author Sheryl
 */
public class VentanaModificar extends javax.swing.JFrame {

    /** Creates new form VentanaModificar */
    public VentanaModificar() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLNombre1 = new javax.swing.JLabel();
        jLNombre2 = new javax.swing.JLabel();
        jTextApellido = new javax.swing.JTextField();
        jLNombre4 = new javax.swing.JLabel();
        jTextNickname = new javax.swing.JTextField();
        jLNombre3 = new javax.swing.JLabel();
        jPClave = new javax.swing.JPasswordField();
        jLNombre5 = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jTextAvatar = new javax.swing.JTextField();
        jDCFechaNac = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jBCancelar = new javax.swing.JButton();
        jBOK = new javax.swing.JButton();
        jBname = new javax.swing.JButton();
        jBlastName = new javax.swing.JButton();
        jBclave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextNombre.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTextNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTextNombre.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Brush Script MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("User data");

        jLNombre1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLNombre1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre1.setText("Name:");

        jLNombre2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLNombre2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre2.setText("Last Name:");

        jTextApellido.setBackground(new java.awt.Color(255, 255, 255));
        jTextApellido.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTextApellido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTextApellido.setEnabled(false);

        jLNombre4.setFont(new java.awt.Font("Calibri", 1, 14));
        jLNombre4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre4.setText("*Nickname:");

        jTextNickname.setBackground(new java.awt.Color(255, 255, 255));
        jTextNickname.setEditable(false);
        jTextNickname.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTextNickname.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jTextNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNicknameActionPerformed(evt);
            }
        });

        jLNombre3.setFont(new java.awt.Font("Calibri", 1, 14));
        jLNombre3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre3.setText("Password:");

        jPClave.setBackground(new java.awt.Color(255, 255, 255));
        jPClave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jPClave.setEnabled(false);

        jLNombre5.setFont(new java.awt.Font("Calibri", 1, 14));
        jLNombre5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre5.setText("Birth Date:");

        jLNombre.setFont(new java.awt.Font("Calibri", 1, 14));
        jLNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombre.setText("Avatar: ");

        jTextAvatar.setBackground(new java.awt.Color(255, 255, 255));
        jTextAvatar.setEditable(false);
        jTextAvatar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jTextAvatar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));

        jDCFechaNac.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));
        jDCFechaNac.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel2.setText("*Estos campos no pueden modificarse");

        jBCancelar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jBCancelar.setForeground(new java.awt.Color(153, 51, 0));
        jBCancelar.setText("Cancel");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBOK.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jBOK.setForeground(new java.awt.Color(153, 51, 0));
        jBOK.setText("OK");
        jBOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOKActionPerformed(evt);
            }
        });

        jBname.setText("...");
        jBname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnameActionPerformed(evt);
            }
        });

        jBlastName.setText("...");
        jBlastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBlastNameActionPerformed(evt);
            }
        });

        jBclave.setText("...");
        jBclave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jDCFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jBOK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jTextAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton1, 0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPClave, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBclave, 0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBlastName, 0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jBname, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBname)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBlastName)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPClave, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBclave)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDCFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBOK)
                    .addComponent(jBCancelar))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Imagenes ventanaImagenes;
        ventanaImagenes = new Imagenes(this, jTextAvatar);
        ventanaImagenes.setVisible(true);
        confirm1 = "4";
}//GEN-LAST:event_jButton1ActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
}//GEN-LAST:event_jBCancelarActionPerformed

    private void jBOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOKActionPerformed
        // TODO add your handling code here:
        if (jTextNombre.getText().equalsIgnoreCase("")
                || jTextApellido.getText().equalsIgnoreCase("")
                || jTextNickname.getText().equalsIgnoreCase("")
                || jPClave.getText().equalsIgnoreCase("")
                || jTextAvatar.getText().equalsIgnoreCase("")
                /* || getFecha(jDCFechaNac).equalsIgnoreCase("")*/) {
            JOptionPane.showMessageDialog(null, "All fields must be written in.");
        } else {
            if (confirm1.equalsIgnoreCase("1")) {
                String mensaje = ConexionJsockets.solicitudServidor8(jTextNickname.getText(), jTextNombre.getText(), confirm1);
            }
            if (confirm1.equalsIgnoreCase("2")) {
                String mensaje = ConexionJsockets.solicitudServidor8(jTextNickname.getText(), jTextApellido.getText(), confirm1);
            }
            if (confirm1.equalsIgnoreCase("3")) {
                String mensaje = ConexionJsockets.solicitudServidor8(jTextNickname.getText(), jPClave.getText(), confirm1);
            }
            if (confirm1.equalsIgnoreCase("4")) {
                String mensaje = ConexionJsockets.solicitudServidor8(jTextNickname.getText(), jTextAvatar.getText(), confirm1);
            }
        }
            

               /* if (mensaje.equals("TRUE")) {
                    System.out.println(mensaje);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Nickname already exists, please try another one.");
                }*/
        
}//GEN-LAST:event_jBOKActionPerformed

    private void jTextNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNicknameActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextNicknameActionPerformed

    private void jBnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnameActionPerformed
        // TODO add your handling code here:
        jTextNombre.enable(true);
        confirm1 = "1";
    }//GEN-LAST:event_jBnameActionPerformed

    private void jBlastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBlastNameActionPerformed
        // TODO add your handling code here:
        jTextApellido.enable(true);
        confirm1 = "2";
    }//GEN-LAST:event_jBlastNameActionPerformed

    private void jBclaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclaveActionPerformed
        // TODO add your handling code here:
        jPClave.enable(true);
        confirm1 = "3";
    }//GEN-LAST:event_jBclaveActionPerformed

    public static String getFecha(JDateChooser Jdc)
     {
        Calendar fechadate;
        fechadate=Jdc.getCalendar();
        SimpleDateFormat xlsDate;
        xlsDate = new SimpleDateFormat("dd/MM/yyyy");
        String auxiliar = xlsDate.format(fechadate.getTime());

        return auxiliar;

      }

    public void setDatosUsuario(String clave, String nickname, String nombre, String apellido, String avatar, String FechaNac) {

        jTextNombre.setText(nombre);
        jTextApellido.setText(apellido);
        jPClave.setText(clave);
        jTextAvatar.setText(avatar);
        jTextNickname.setText(nickname);


    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaModificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBOK;
    private javax.swing.JButton jBclave;
    private javax.swing.JButton jBlastName;
    private javax.swing.JButton jBname;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDCFechaNac;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNombre1;
    private javax.swing.JLabel jLNombre2;
    private javax.swing.JLabel jLNombre3;
    private javax.swing.JLabel jLNombre4;
    private javax.swing.JLabel jLNombre5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPClave;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextAvatar;
    private javax.swing.JTextField jTextNickname;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables

    static String confirm1 = "0";
}
