/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaJuego.java
 *
 * Created on 08-ago-2010, 21:17:21
 */
package cliente.presentacion;

import javax.swing.*;
import cliente.logica.ConexionJsockets;

/**
 *
 * @author CASITA
 */
public class VentanaJuego extends javax.swing.JFrame {

    /** Creates new form VentanaJuego */
    public VentanaJuego(JFrame ventanaPadre, String nickname, String mensaje) {
        initComponents();
        this.ventanaPadre = ventanaPadre;
        this.nickname = nickname;
        this.mensaje = mensaje;
        this.piedrasEnMano = inicializarPiedrasEnMano();
        inicializarMesa();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton181 = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton182 = new javax.swing.JButton();
        jButton177 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton178 = new javax.swing.JButton();
        jBMesa45 = new javax.swing.JButton();
        jBMesa40 = new javax.swing.JButton();
        jBMesa29 = new javax.swing.JButton();
        jBMesa27 = new javax.swing.JButton();
        jBMesa52 = new javax.swing.JButton();
        jBMesa53 = new javax.swing.JButton();
        jBMesa28 = new javax.swing.JButton();
        jBMesa46 = new javax.swing.JButton();
        jBMesa47 = new javax.swing.JButton();
        jBMesa48 = new javax.swing.JButton();
        jBMesa41 = new javax.swing.JButton();
        jBMesa35 = new javax.swing.JButton();
        jBMesa30 = new javax.swing.JButton();
        jBMesa36 = new javax.swing.JButton();
        jBMesa49 = new javax.swing.JButton();
        jBMesa02 = new javax.swing.JButton();
        jBMesa23 = new javax.swing.JButton();
        jBMesa26 = new javax.swing.JButton();
        jBMesa20 = new javax.swing.JButton();
        jBMesa21 = new javax.swing.JButton();
        jBMesa51 = new javax.swing.JButton();
        jBMesa17 = new javax.swing.JButton();
        jBMesa55 = new javax.swing.JButton();
        jBMesa50 = new javax.swing.JButton();
        jBMesa56 = new javax.swing.JButton();
        jBMesa00 = new javax.swing.JButton();
        jBMesa44 = new javax.swing.JButton();
        jBMesa05 = new javax.swing.JButton();
        jBMesa42 = new javax.swing.JButton();
        jBMesa19 = new javax.swing.JButton();
        jBMesa18 = new javax.swing.JButton();
        jBMesa04 = new javax.swing.JButton();
        jBMesa03 = new javax.swing.JButton();
        jBMesa38 = new javax.swing.JButton();
        jBMesa11 = new javax.swing.JButton();
        jBMesa12 = new javax.swing.JButton();
        jBMesa16 = new javax.swing.JButton();
        jBMesa15 = new javax.swing.JButton();
        jBMesa14 = new javax.swing.JButton();
        jBMesa10 = new javax.swing.JButton();
        jBMesa39 = new javax.swing.JButton();
        jBMesa22 = new javax.swing.JButton();
        jBMesa24 = new javax.swing.JButton();
        jBMesa37 = new javax.swing.JButton();
        jBMesa25 = new javax.swing.JButton();
        jBMesa31 = new javax.swing.JButton();
        jBMesa13 = new javax.swing.JButton();
        jBMesa09 = new javax.swing.JButton();
        jBMesa08 = new javax.swing.JButton();
        jBMesa54 = new javax.swing.JButton();
        jBMesa59 = new javax.swing.JButton();
        jBMesa57 = new javax.swing.JButton();
        jBMesa58 = new javax.swing.JButton();
        jBMesa06 = new javax.swing.JButton();
        jBMesa01 = new javax.swing.JButton();
        jBMesa43 = new javax.swing.JButton();
        jBMesa32 = new javax.swing.JButton();
        jBMesa34 = new javax.swing.JButton();
        jBMesa33 = new javax.swing.JButton();
        jBMesa07 = new javax.swing.JButton();
        jBPiedra7 = new javax.swing.JButton();
        jBPiedra3 = new javax.swing.JButton();
        jBPiedra1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBPiedra2 = new javax.swing.JButton();
        jBPiedra4 = new javax.swing.JButton();
        jBPiedra6 = new javax.swing.JButton();
        jBPiedra5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButtonPot = new javax.swing.JButton();
        jButtonPass = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBRotarIzq = new javax.swing.JButton();
        jBRotarDer = new javax.swing.JButton();
        jBPiedra8 = new javax.swing.JButton();
        jBPiedra9 = new javax.swing.JButton();
        jBPiedra10 = new javax.swing.JButton();
        jBPiedra11 = new javax.swing.JButton();
        jBPiedra12 = new javax.swing.JButton();
        jBPiedra13 = new javax.swing.JButton();
        jBPiedra14 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel4.setText("Game #");

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 24));
        jLabel5.setText("iDomino");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel3.setText("Computadora");

        jBMesa45.setName("jBMesa45"); // NOI18N
        jBMesa45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa40.setName("jBMesa40"); // NOI18N
        jBMesa40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa29.setName("jBMesa29"); // NOI18N
        jBMesa29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa27.setName("jBMesa27"); // NOI18N
        jBMesa27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa52.setName("jBMesa52"); // NOI18N
        jBMesa52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa53.setName("jBMesa53"); // NOI18N
        jBMesa53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa28.setName("jBMesa28"); // NOI18N
        jBMesa28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa46.setName("jBMesa46"); // NOI18N
        jBMesa46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa47.setName("jBMesa47"); // NOI18N
        jBMesa47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa48.setName("jBMesa48"); // NOI18N
        jBMesa48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa41.setName("jBMesa41"); // NOI18N
        jBMesa41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa35.setName("jBMesa35"); // NOI18N
        jBMesa35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa30.setName("jBMesa30"); // NOI18N
        jBMesa30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa36.setName("jBMesa36"); // NOI18N
        jBMesa36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa49.setName("jBMesa49"); // NOI18N
        jBMesa49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa02.setName("jBMesa02"); // NOI18N
        jBMesa02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa23.setName("jBMesa23"); // NOI18N
        jBMesa23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa26.setName("jBMesa26"); // NOI18N
        jBMesa26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa20.setName("jBMesa20"); // NOI18N
        jBMesa20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa21.setName("jBMesa21"); // NOI18N
        jBMesa21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa51.setName("jBMesa51"); // NOI18N
        jBMesa51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa17.setName("jBMesa17"); // NOI18N
        jBMesa17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa55.setName("jBMesa55"); // NOI18N
        jBMesa55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa50.setName("jBMesa50"); // NOI18N
        jBMesa50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa56.setName("jBMesa56"); // NOI18N
        jBMesa56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa00.setName("jBMesa00"); // NOI18N
        jBMesa00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa44.setName("jBMesa44"); // NOI18N
        jBMesa44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa05.setName("jBMesa05"); // NOI18N
        jBMesa05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa42.setName("jBMesa42"); // NOI18N
        jBMesa42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa19.setName("jBMesa19"); // NOI18N
        jBMesa19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa18.setName("jBMesa18"); // NOI18N
        jBMesa18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa04.setName("jBMesa04"); // NOI18N
        jBMesa04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa03.setName("jBMesa03"); // NOI18N
        jBMesa03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa38.setName("jBMesa38"); // NOI18N
        jBMesa38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa11.setName("jBMesa11"); // NOI18N
        jBMesa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa12.setName("jBMesa12"); // NOI18N
        jBMesa12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa16.setName("jBMesa16"); // NOI18N
        jBMesa16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa15.setName("jBMesa15"); // NOI18N
        jBMesa15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa14.setName("jBMesa14"); // NOI18N
        jBMesa14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa10.setName("jBMesa10"); // NOI18N
        jBMesa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa39.setName("jBMesa39"); // NOI18N
        jBMesa39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa22.setName("jBMesa22"); // NOI18N
        jBMesa22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa24.setName("jBMesa24"); // NOI18N
        jBMesa24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa37.setName("jBMesa37"); // NOI18N
        jBMesa37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa25.setName("jBMesa25"); // NOI18N
        jBMesa25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa31.setName("jBMesa31"); // NOI18N
        jBMesa31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa13.setName("jBMesa13"); // NOI18N
        jBMesa13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa09.setName("jBMesa09"); // NOI18N
        jBMesa09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa08.setName("jBMesa08"); // NOI18N
        jBMesa08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa54.setName("jBMesa54"); // NOI18N
        jBMesa54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa59.setName("jBMesa59"); // NOI18N
        jBMesa59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa57.setName("jBMesa57"); // NOI18N
        jBMesa57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa58.setName("jBMesa58"); // NOI18N
        jBMesa58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa06.setName("jBMesa06"); // NOI18N
        jBMesa06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa01.setName("jBMesa01"); // NOI18N
        jBMesa01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa43.setName("jBMesa43"); // NOI18N
        jBMesa43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa32.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBMesa32.setName("jBMesa32"); // NOI18N
        jBMesa32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa34.setName("jBMesa34"); // NOI18N
        jBMesa34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa33.setAutoscrolls(true);
        jBMesa33.setName("jBMesa33"); // NOI18N
        jBMesa33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBMesa07.setName("jBMesa07"); // NOI18N
        jBMesa07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraDelTableroActionPerformed(evt);
            }
        });

        jBPiedra7.setName("jBPiedra7"); // NOI18N
        jBPiedra7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra3.setName("jBPiedra3"); // NOI18N
        jBPiedra3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra1.setName("jBPiedra1"); // NOI18N
        jBPiedra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jLabel1.setText("Player");

        jBPiedra2.setName("jBPiedra2"); // NOI18N
        jBPiedra2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra4.setName("jBPiedra4"); // NOI18N
        jBPiedra4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra6.setName("6"); // NOI18N
        jBPiedra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra5.setName("jBPiedra5"); // NOI18N
        jBPiedra5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24));
        jLabel2.setText("POT");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel6.setText("Game #");

        jButtonPot.setText("Pot");
        jButtonPot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPotActionPerformed(evt);
            }
        });

        jButtonPass.setText("Pass");
        jButtonPass.setName("jButtonPass"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 24));
        jLabel7.setText("iDomino");

        jBRotarIzq.setText("RotI");
        jBRotarIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRotarIzqActionPerformed(evt);
            }
        });

        jBRotarDer.setText("RotD");
        jBRotarDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRotarDerActionPerformed(evt);
            }
        });

        jBPiedra8.setName("jBPiedra1"); // NOI18N
        jBPiedra8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra9.setName("jBPiedra2"); // NOI18N
        jBPiedra9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra10.setName("jBPiedra3"); // NOI18N
        jBPiedra10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra11.setName("jBPiedra4"); // NOI18N
        jBPiedra11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra12.setName("jBPiedra5"); // NOI18N
        jBPiedra12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra13.setName("6"); // NOI18N
        jBPiedra13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        jBPiedra14.setName("jBPiedra7"); // NOI18N
        jBPiedra14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPiedraSeleccionadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBMesa00, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa01, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa02, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa03, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa04, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa05, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa06, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa07, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa08, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa09, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBMesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa16, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa17, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa18, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa19, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBMesa30, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa31, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa32, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa33, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa34, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa35, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa36, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa37, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa38, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa39, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBMesa20, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa21, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa22, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa23, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa24, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa25, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa26, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa27, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa28, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa29, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBMesa40, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa41, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa42, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa43, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa44, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa45, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa46, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa47, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa48, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa49, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBMesa50, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa51, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa52, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa53, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa54, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa55, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa56, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa57, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa58, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBMesa59, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton179, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton181, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton177, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton178, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton176, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton182, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton180, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBPiedra8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra13, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra14, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBPiedra1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBPiedra7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jBRotarIzq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBRotarDer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonPot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addComponent(jButtonPass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5)))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton180, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton182, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton176, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton178, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton177, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton181, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton179, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBMesa06, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa05, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa04, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa03, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa02, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa01, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa00, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa07, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa08, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa09, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBMesa19, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa18, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa17, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa16, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBMesa26, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa25, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa24, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa23, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa22, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa21, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa20, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa27, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa28, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa29, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBMesa39, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa38, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa37, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa36, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa35, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa33, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa32, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa31, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa30, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa34, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBMesa49, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa48, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa47, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa46, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa45, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa43, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa42, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa41, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa40, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa44, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jBMesa56, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa55, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa54, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa53, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa52, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa51, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa50, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa57, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa58, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBMesa59, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jBPiedra7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBPiedra6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBPiedra5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBPiedra4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBPiedra3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBPiedra2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jBPiedra1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jBPiedra14, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBPiedra13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBPiedra12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBPiedra11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBPiedra10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBPiedra9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jBPiedra8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel1)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBRotarIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jBRotarDer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jButtonPot, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPass, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarMesa() {
        int i, j;

        final JButton arregloBotones[][] = {
            {jBMesa00, jBMesa01, jBMesa02, jBMesa03, jBMesa04, jBMesa05, jBMesa06, jBMesa07, jBMesa08, jBMesa09},
            {jBMesa10, jBMesa11, jBMesa12, jBMesa13, jBMesa14, jBMesa15, jBMesa16, jBMesa17, jBMesa18, jBMesa19},
            {jBMesa20, jBMesa21, jBMesa22, jBMesa23, jBMesa24, jBMesa25, jBMesa26, jBMesa27, jBMesa28, jBMesa29},
            {jBMesa30, jBMesa31, jBMesa32, jBMesa33, jBMesa34, jBMesa35, jBMesa36, jBMesa37, jBMesa38, jBMesa39},
            {jBMesa40, jBMesa41, jBMesa42, jBMesa43, jBMesa44, jBMesa45, jBMesa46, jBMesa47, jBMesa48, jBMesa49},
            {jBMesa50, jBMesa51, jBMesa52, jBMesa53, jBMesa54, jBMesa55, jBMesa56, jBMesa57, jBMesa58, jBMesa59}
        };

        JButton botonActual;

        for (i = 0; i < 6; i++) {
            for (j = 0; j < 10; j++) {
                botonActual = arregloBotones[i][j];

                botonActual.setIcon(null);

                //botonActual.setEnabled(false);

                botonActual.setFocusable(false);
            }
        }


        botonActualSeleccionado = null;
    }

    private JButton[] inicializarPiedrasEnMano() {
        int i, j;

        final JButton arregloBotones[] = {jBPiedra1, jBPiedra2, jBPiedra3, jBPiedra4, jBPiedra5, jBPiedra6, jBPiedra7,
            jBPiedra8, jBPiedra9, jBPiedra10, jBPiedra11, jBPiedra12, jBPiedra13, jBPiedra14};

        JButton botonActual;

        String[] subArg = mensaje.split(":");

        for (i = 0; i < 7; i++) {
            botonActual = arregloBotones[i];

            String mensajeActual = subArg[i];

            botonActual.setIcon(new javax.swing.ImageIcon(getClass().getResource(obtenerImagenPiedra(mensajeActual))));

            /*String nombreBoton = botonActual.getIcon().toString();
            System.out.println("imagen: " + nombreBoton.substring(nombreBoton.length()-13, nombreBoton.length()-4));*/

            botonActual.setEnabled(true);
        }

        for (i = 7; i < 14; i++) {
            botonActual = arregloBotones[i];
            //botonActual.setEnabled(false);
            botonActual.setVisible(false);
        }

        jBPiedra1.requestFocus();
        return arregloBotones;
    }

    public static String obtenerImagenPiedra(String mensaje) {
        String img = "";
        String direccion = "/cliente/presentacion/resources/Piedras/";

        String[] subArg2 = mensaje.split("-");

        return img = direccion + subArg2[3];
    }

    public static String cambiarImagenPiedra(boolean rotarDerecha, int indice, String imagenAsociadaActual) {

        if (rotarDerecha) {
            indice++;

            if (indice == 4) {
                indice = 0;
            }
        } else {
            indice--;

            if (indice == -1) {
                indice = 3;
            }
        }

        String stringIndice = Integer.toString(indice);

        imagenAsociadaActual = imagenAsociadaActual.substring(0, imagenAsociadaActual.length() - 1) + stringIndice + ".png";

        return imagenAsociadaActual;
    }

    public static String rotarPiedra(JButton botonPiedra, boolean rotarDerecha) {
        String direccion = "/cliente/presentacion/resources/Piedras/";
        String fuente, indiceString, nombreBoton, imagenAsociada;
        fuente = indiceString = nombreBoton = imagenAsociada = "";
        int indicePiedra;

        nombreBoton = botonPiedra.getIcon().toString();

        //PARA HALLAR LA IMAGEN ASOCIADA
        imagenAsociada = nombreBoton.substring(nombreBoton.length() - 13, nombreBoton.length() - 4);
        System.out.println("Imagen Asociada: " + imagenAsociada);

        //PARA HALLAR EL INDICE BEGIN
        //indiceString = nombreBoton.substring(NombreBotonSize - 5, NombreBotonSize - 4);
        indiceString = imagenAsociada.substring(imagenAsociada.length() - 1);

        System.out.println("indice= " + indiceString);

        indicePiedra = Integer.parseInt(indiceString);

        //PARA HALLAR EL INDICE END.        

        String imagenAsociadaActual = cambiarImagenPiedra(rotarDerecha, indicePiedra, imagenAsociada);

        System.out.println("Imagen Asociada Actualizada: " + imagenAsociadaActual);

        fuente = direccion + imagenAsociadaActual;

        System.out.println("fuente: " + fuente);


        return fuente;
    }

    public String obtenerCadenaPiedra(String direccionIcono, String mensaje) {

        String[] subArg = mensaje.split(":");
        String cadenaPiedra = "";
        String num1 = direccionIcono.substring(direccionIcono.length() - 13, direccionIcono.length() - 12);
        String num2 = direccionIcono.substring(direccionIcono.length() - 12, direccionIcono.length() - 11);
        cadenaPiedra = num1 + "-" + num2;

        return cadenaPiedra;
    }

    public String obtenerImagenAsociada(String direccionIcono, String mensaje) {

        String[] subArg = mensaje.split(":");
        int i, j;
        String imagenActual = "";
        String img = direccionIcono.substring(direccionIcono.length() - 13);

        for (i = 0; i < 7; i++) {

            String mensajeActual = subArg[i];

            String[] subArg2 = mensajeActual.split("-");

            for (j = 3; j < 7; j++) {

                if (subArg2[j].equalsIgnoreCase(img)) {
                    imagenActual = subArg2[j];
                }
            }
        }
        return imagenActual;
    }

    private void jBPiedraSeleccionadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPiedraSeleccionadaActionPerformed
        // TODO add your handling code here:
        JButton boton = (JButton) evt.getSource();

        botonActualSeleccionado = boton;
    }//GEN-LAST:event_jBPiedraSeleccionadaActionPerformed

    private void jBPiedraDelTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPiedraDelTableroActionPerformed
        // TODO add your handling code here:
        JButton boton = (JButton) evt.getSource();

        if (botonActualSeleccionado != null) {
            boton.setIcon(botonActualSeleccionado.getIcon());

            System.out.println("nombre de boton: " + boton.getName());

            String posX = boton.getName().toString();
            posX = posX.substring(posX.length() - 2, posX.length() - 1);

            String posY = boton.getName().toString();
            posY = posY.substring(posY.length() - 1);


            String posicion = posX + "-" + posY;

            String cadenaPiedra = obtenerCadenaPiedra(boton.getIcon().toString(), mensaje);

            String cadenaImagen = obtenerImagenAsociada(boton.getIcon().toString(), mensaje);

            System.out.println("nickname: " + nickname);
            System.out.println("piedra: " + cadenaPiedra);
            System.out.println("posicion: " + posicion);
            System.out.println("imagenSeleccionada: " + cadenaImagen);

            String cadena = ConexionJsockets.solicitudServidor5(nickname, cadenaPiedra, posicion, cadenaImagen);

            botonActualSeleccionado.setIcon(null);
            botonActualSeleccionado.setEnabled(false);

        }
    }//GEN-LAST:event_jBPiedraDelTableroActionPerformed

    private void jBRotarIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRotarIzqActionPerformed
        // TODO add your handling code here:
        if (botonActualSeleccionado != null && botonActualSeleccionado.isEnabled()) {
            botonActualSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource(rotarPiedra(botonActualSeleccionado, false))));

            botonActualSeleccionado.requestFocus();
        }

    }//GEN-LAST:event_jBRotarIzqActionPerformed

    private void jBRotarDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRotarDerActionPerformed
        // TODO add your handling code here:
        if (botonActualSeleccionado != null && botonActualSeleccionado.isEnabled()) {
            botonActualSeleccionado.setIcon(new javax.swing.ImageIcon(getClass().getResource(rotarPiedra(botonActualSeleccionado, true))));

            botonActualSeleccionado.requestFocus();
        }
    }//GEN-LAST:event_jBRotarDerActionPerformed

    private void jButtonPotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPotActionPerformed
        // TODO add your handling code here:
        String cadena = ConexionJsockets.solicitudServidor7(nickname);

        System.out.println("cadena: " + cadena);

        String subArg[] = cadena.split(":");

        System.out.println("direccion: " + subArg[0]);

        String imagenPiedra = obtenerImagenPiedra(subArg[1]);
        int i = 0;
        boolean piedraPuesta = false;

        while (!piedraPuesta && i > -1 && i < 7) {
            //for (i = 0; i < 7; i++) {
            if (!piedrasEnMano[i].isEnabled()) {
                piedrasEnMano[i].setEnabled(true);
                piedrasEnMano[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(imagenPiedra)));
                piedraPuesta = true;
            }
            i++;
        }

        while (!piedraPuesta && i > 6 && i < 14) {
            //for (i = 7; i < 14; i++) {
            if (!piedrasEnMano[i].isEnabled()) {
                piedrasEnMano[i].setEnabled(true);
                piedrasEnMano[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(imagenPiedra)));
                piedraPuesta = true;
            } else if (piedrasEnMano[i].getIcon() == null) {
                piedrasEnMano[i].setVisible(true);
                piedrasEnMano[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(imagenPiedra)));
                piedraPuesta = true;
            }
            i++;
        }


    }//GEN-LAST:event_jButtonPotActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaJuego(null, "", "").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMesa00;
    private javax.swing.JButton jBMesa01;
    private javax.swing.JButton jBMesa02;
    private javax.swing.JButton jBMesa03;
    private javax.swing.JButton jBMesa04;
    private javax.swing.JButton jBMesa05;
    private javax.swing.JButton jBMesa06;
    private javax.swing.JButton jBMesa07;
    private javax.swing.JButton jBMesa08;
    private javax.swing.JButton jBMesa09;
    private javax.swing.JButton jBMesa10;
    private javax.swing.JButton jBMesa11;
    private javax.swing.JButton jBMesa12;
    private javax.swing.JButton jBMesa13;
    private javax.swing.JButton jBMesa14;
    private javax.swing.JButton jBMesa15;
    private javax.swing.JButton jBMesa16;
    private javax.swing.JButton jBMesa17;
    private javax.swing.JButton jBMesa18;
    private javax.swing.JButton jBMesa19;
    private javax.swing.JButton jBMesa20;
    private javax.swing.JButton jBMesa21;
    private javax.swing.JButton jBMesa22;
    private javax.swing.JButton jBMesa23;
    private javax.swing.JButton jBMesa24;
    private javax.swing.JButton jBMesa25;
    private javax.swing.JButton jBMesa26;
    private javax.swing.JButton jBMesa27;
    private javax.swing.JButton jBMesa28;
    private javax.swing.JButton jBMesa29;
    private javax.swing.JButton jBMesa30;
    private javax.swing.JButton jBMesa31;
    private javax.swing.JButton jBMesa32;
    private javax.swing.JButton jBMesa33;
    private javax.swing.JButton jBMesa34;
    private javax.swing.JButton jBMesa35;
    private javax.swing.JButton jBMesa36;
    private javax.swing.JButton jBMesa37;
    private javax.swing.JButton jBMesa38;
    private javax.swing.JButton jBMesa39;
    private javax.swing.JButton jBMesa40;
    private javax.swing.JButton jBMesa41;
    private javax.swing.JButton jBMesa42;
    private javax.swing.JButton jBMesa43;
    private javax.swing.JButton jBMesa44;
    private javax.swing.JButton jBMesa45;
    private javax.swing.JButton jBMesa46;
    private javax.swing.JButton jBMesa47;
    private javax.swing.JButton jBMesa48;
    private javax.swing.JButton jBMesa49;
    private javax.swing.JButton jBMesa50;
    private javax.swing.JButton jBMesa51;
    private javax.swing.JButton jBMesa52;
    private javax.swing.JButton jBMesa53;
    private javax.swing.JButton jBMesa54;
    private javax.swing.JButton jBMesa55;
    private javax.swing.JButton jBMesa56;
    private javax.swing.JButton jBMesa57;
    private javax.swing.JButton jBMesa58;
    private javax.swing.JButton jBMesa59;
    private javax.swing.JButton jBPiedra1;
    private javax.swing.JButton jBPiedra10;
    private javax.swing.JButton jBPiedra11;
    private javax.swing.JButton jBPiedra12;
    private javax.swing.JButton jBPiedra13;
    private javax.swing.JButton jBPiedra14;
    private javax.swing.JButton jBPiedra2;
    private javax.swing.JButton jBPiedra3;
    private javax.swing.JButton jBPiedra4;
    private javax.swing.JButton jBPiedra5;
    private javax.swing.JButton jBPiedra6;
    private javax.swing.JButton jBPiedra7;
    private javax.swing.JButton jBPiedra8;
    private javax.swing.JButton jBPiedra9;
    private javax.swing.JButton jBRotarDer;
    private javax.swing.JButton jBRotarIzq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton177;
    private javax.swing.JButton jButton178;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton182;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonPass;
    private javax.swing.JButton jButtonPot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollBar jScrollBar1;
    // End of variables declaration//GEN-END:variables
    JButton botonActualSeleccionado;
    JFrame ventanaPadre;
    String nickname;
    String mensaje;
    JButton[] piedrasEnMano;
}
