/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaMenu.java
 *
 * Created on 08/08/2010, 10:10:02 AM
 */
package cliente.presentacion;

import javax.swing.JFrame;
import cliente.logica.ConexionJsockets;

/**
 *
 * @author Alberly
 */
public class VentanaMenu extends javax.swing.JFrame {

    javax.swing.JFrame ventanaPadre;

    /** Creates new form VentanaMenu */
    public VentanaMenu() {
        initComponents();
    }

    public VentanaMenu(JFrame ventanaPadre) {
        initComponents();
        this.ventanaPadre = ventanaPadre;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBCrearPartida = new javax.swing.JButton();
        jBCargarPartida = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jLBienvenida = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextNickname = new javax.swing.JTextField();
        jLavatar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Welcome to iDomino");

        jBCrearPartida.setFont(new java.awt.Font("Calibri", 0, 12));
        jBCrearPartida.setText("New Game");
        jBCrearPartida.setName("jBCrearPartida"); // NOI18N
        jBCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearPartidaActionPerformed(evt);
            }
        });

        jBCargarPartida.setFont(new java.awt.Font("Calibri", 0, 12));
        jBCargarPartida.setText("Load Game");

        jBModificar.setFont(new java.awt.Font("Calibri", 0, 12));
        jBModificar.setText("Modify Info");

        jLBienvenida.setFont(new java.awt.Font("Corbel", 0, 24));

        jTextNombre.setEditable(false);
        jTextNombre.setFont(new java.awt.Font("Calibri", 1, 12));
        jTextNombre.setBorder(null);
        jTextNombre.setSelectionColor(new java.awt.Color(51, 51, 255));
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });

        jTextApellido.setEditable(false);
        jTextApellido.setFont(new java.awt.Font("Calibri", 1, 12));
        jTextApellido.setBorder(null);
        jTextApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApellidoActionPerformed(evt);
            }
        });

        jLNombre.setFont(new java.awt.Font("Calibri", 0, 12));
        jLNombre.setText("Name:");

        jLApellido.setFont(new java.awt.Font("Calibri", 0, 12));
        jLApellido.setText("LastName:");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 12));
        jLabel1.setText("Nickname:");

        jTextNickname.setEditable(false);
        jTextNickname.setFont(new java.awt.Font("Calibri", 1, 12));
        jTextNickname.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLApellido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextApellido))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLNombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLavatar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBCrearPartida)
                            .addComponent(jBCargarPartida)
                            .addComponent(jBModificar))
                        .addGap(91, 91, 91))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLavatar, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCrearPartida)
                        .addGap(18, 18, 18)
                        .addComponent(jBCargarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombre)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLApellido)
                            .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBModificar)))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApellidoActionPerformed

    private void jBCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearPartidaActionPerformed
        // TODO add your handling code here:
        String mensaje = ConexionJsockets.solicitudServidor2(jTextNickname, "fechaInicio");

        new VentanaJuego(this, jTextNickname.getText(), mensaje).setVisible(true);
    }//GEN-LAST:event_jBCrearPartidaActionPerformed

    public void setDatosUsuario(String nickname, String nombre, String apellido, String avatar) {
        jTextNickname.setText(nickname);
        jTextNombre.setText(nombre);
        jTextApellido.setText(apellido);
        //jTexIcono.setText(avatar);
        if (avatar.equalsIgnoreCase("Dog")) {
            jLavatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/presentacion/resources/Imagen10.jpg")));
        } else if (avatar.equalsIgnoreCase("Umbrella")) {
            jLavatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/presentacion/resources/Imagen8.png")));
        } else if (avatar.equalsIgnoreCase("Turtle")) {
            jLavatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/presentacion/resources/Imagen9.png")));
        } else if (avatar.equalsIgnoreCase("Butterfly")) {
            jLavatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/presentacion/resources/Imagen6.png")));
        } else if (avatar.equalsIgnoreCase("Bug")) {
            jLavatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/presentacion/resources/Imagen12.png")));
        } else if (avatar.equalsIgnoreCase("Domino")) {
            jLavatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cliente/presentacion/resources/Imagen13.png")));
        }

        jLBienvenida.setText(" Welcome " + nickname + " to iDomino");

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCargarPartida;
    private javax.swing.JButton jBCrearPartida;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLBienvenida;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLavatar;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextNickname;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
